/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'Keil_DWT_Project' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

/* ARM::CMSIS-Compiler:File Interface:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_File_Interface        /* Compiler File Interface */
#define RTE_CMSIS_Compiler_File_Interface_Breakpoint /* Compiler File Interface: Breakpoint */
/* ARM::CMSIS-Compiler:File Interface:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_File_Interface        /* Compiler File Interface */
#define RTE_CMSIS_Compiler_File_Interface_Custom /* Compiler File Interface: Custom */
/* ARM::CMSIS-Compiler:OS Interface:CMSIS-RTOS2@2.1.0 */
#define RTE_CMSIS_Compiler_OS_Interface       /* Compiler OS Interface */
#define RTE_CMSIS_Compiler_OS_Interface_RTOS2 /* Compiler OS Interface: CMSIS-RTOS2 */
/* Features */
#define RTE_CMSIS_Compiler_OS_Interface_RTOS2_LOCKS     /* Implements _mutex functions */
#define RTE_CMSIS_Compiler_OS_Interface_RTOS2_LIBSPACE  /* Implements per-thread static data management */
/* ARM::CMSIS-Compiler:OS Interface:Custom@2.1.0 */
#define RTE_CMSIS_Compiler_OS_Interface        /* Compiler OS Interface */
#define RTE_CMSIS_Compiler_OS_Interface_Custom /* Compiler OS Interface: Custom */
/* ARM::CMSIS-Compiler:STDERR:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Breakpoint     /* CMSIS-Compiler STDERR: Breakpoint */
/* ARM::CMSIS-Compiler:STDERR:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Custom         /* CMSIS-Compiler STDERR: Custom */
/* ARM::CMSIS-Compiler:STDERR:Event Recorder@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_Event_Recorder /* CMSIS-Compiler STDERR: Event Recorder */
/* ARM::CMSIS-Compiler:STDERR:ITM@1.1.0 */
#define RTE_CMSIS_Compiler_STDERR                /* CMSIS-Compiler STDERR */
#define RTE_CMSIS_Compiler_STDERR_ITM            /* CMSIS-Compiler STDERR: ITM */
/* ARM::CMSIS-Compiler:STDIN:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Breakpoint      /* CMSIS-Compiler STDIN: Breakpoint */
/* ARM::CMSIS-Compiler:STDIN:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_Custom          /* CMSIS-Compiler STDIN: Custom */
/* ARM::CMSIS-Compiler:STDIN:ITM@1.1.0 */
#define RTE_CMSIS_Compiler_STDIN                 /* CMSIS-Compiler STDIN */
#define RTE_CMSIS_Compiler_STDIN_ITM             /* CMSIS-Compiler STDIN: ITM */
/* ARM::CMSIS-Compiler:STDOUT:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Breakpoint     /* CMSIS-Compiler STDOUT: Breakpoint */
/* ARM::CMSIS-Compiler:STDOUT:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Custom         /* CMSIS-Compiler STDOUT: Custom */
/* ARM::CMSIS-Compiler:STDOUT:Event Recorder@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_Event_Recorder /* CMSIS-Compiler STDOUT: Event Recorder */
/* ARM::CMSIS-Compiler:STDOUT:ITM@1.1.0 */
#define RTE_CMSIS_Compiler_STDOUT                /* CMSIS-Compiler STDOUT */
#define RTE_CMSIS_Compiler_STDOUT_ITM            /* CMSIS-Compiler STDOUT: ITM */
/* ARM::CMSIS-Compiler:TTY:Breakpoint@1.1.0 */
#define RTE_CMSIS_Compiler_TTY                   /* CMSIS-Compiler TTY */
#define RTE_CMSIS_Compiler_TTY_Breakpoint        /* CMSIS-Compiler TTY: Breakpoint */
/* ARM::CMSIS-Compiler:TTY:Custom@1.1.0 */
#define RTE_CMSIS_Compiler_TTY                   /* CMSIS-Compiler TTY */
#define RTE_CMSIS_Compiler_TTY_Custom            /* CMSIS-Compiler TTY: Custom */
/* ARM::CMSIS-Compiler:TTY:ITM@1.1.0 */
#define RTE_CMSIS_Compiler_TTY                   /* CMSIS-Compiler TTY */
#define RTE_CMSIS_Compiler_TTY_ITM               /* CMSIS-Compiler TTY: ITM */
/* ARM::CMSIS:RTOS2:Keil RTX5&Library@5.9.0 */
#define RTE_CMSIS_RTOS2                 /* CMSIS-RTOS2 */
#define RTE_CMSIS_RTOS2_RTX5            /* CMSIS-RTOS2 Keil RTX5 */
/* Keil::CMSIS Driver:GPIO@1.0.0 */
#define RTE_Drivers_GPIO0               /* Driver GPIO0 */
/* Keil::CMSIS Driver:I2C:Multi-Slave@1.0.1 */
#define RTE_Drivers_I2C_MultiSlave      /* Driver I2C Multi-Slave */
/* Keil::CMSIS Driver:I2C@3.0.0 */
#define RTE_Drivers_I2C1                /* Driver I2C1 */
#define RTE_Drivers_I2C2                /* Driver I2C2 */
#define RTE_Drivers_I2C3                /* Driver I2C3 */
#define RTE_Drivers_I2C4                /* Driver I2C4 */
#define RTE_Drivers_I2C5                /* Driver I2C5 */
#define RTE_Drivers_I2C6                /* Driver I2C6 */
#define RTE_Drivers_I2C7                /* Driver I2C7 */
#define RTE_Drivers_I2C8                /* Driver I2C8 */
/* Keil::CMSIS Driver:SPI:Multi-Slave@1.0.1 */
#define RTE_Drivers_SPI_MultiSlave      /* Driver SPI Multi-Slave */
/* Keil::CMSIS Driver:SPI@3.0.0 */
#define RTE_Drivers_SPI1                /* Driver SPI1 */
#define RTE_Drivers_SPI2                /* Driver SPI2 */
#define RTE_Drivers_SPI3                /* Driver SPI3 */
#define RTE_Drivers_SPI4                /* Driver SPI4 */
#define RTE_Drivers_SPI5                /* Driver SPI5 */
#define RTE_Drivers_SPI6                /* Driver SPI6 */
#define RTE_Drivers_SPI7                /* Driver SPI7 */
#define RTE_Drivers_SPI8                /* Driver SPI8 */
/* Keil::CMSIS Driver:USART:CDC@1.10.0 */
#define RTE_Drivers_USART_CDC_ACM       /* Driver USART CDC ACM */
/* Keil::CMSIS Driver:USART:PL2303@1.10.0 */
#define RTE_Drivers_USART_PL2303        /* Driver USART PL2303 */
/* Keil::CMSIS Driver:USART@3.0.0 */
#define RTE_CMSIS_Driver_USART1         /* Driver USART1  */
#define RTE_CMSIS_Driver_USART2         /* Driver USART2  */
#define RTE_CMSIS_Driver_USART3         /* Driver USART3  */
#define RTE_CMSIS_Driver_USART4         /* Driver USART4  */
#define RTE_CMSIS_Driver_USART5         /* Driver USART5  */
#define RTE_CMSIS_Driver_USART6         /* Driver USART6  */
#define RTE_CMSIS_Driver_USART7         /* Driver USART7  */
#define RTE_CMSIS_Driver_USART8         /* Driver USART8  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART9         /* Driver USART9  */
#define RTE_CMSIS_Driver_USART10        /* Driver USART10 */
#define RTE_CMSIS_Driver_USART11        /* Driver USART11 */
#define RTE_CMSIS_Driver_USART12        /* Driver USART12 */
#define RTE_CMSIS_Driver_USART13        /* Driver USART13 */
#define RTE_CMSIS_Driver_USART14        /* Driver USART14 */
#define RTE_CMSIS_Driver_USART15        /* Driver USART15 */
#define RTE_CMSIS_Driver_USART21        /* Driver USART21 (LPUART1) */
#define RTE_CMSIS_Driver_USART22        /* Driver USART22 (LPUART2) */
#define RTE_CMSIS_Driver_USART23        /* Driver USART23 (LPUART3) */
/* Keil::CMSIS-Compiler:File Interface:MDK-MW File System@1.0.0 */
#define RTE_CMSIS_Compiler_File_Interface        /* CMSIS-Compiler File Interface */
#define RTE_CMSIS_Compiler_File_Interface_MDK_MW /* CMSIS-Compiler File Interface: MDK-Middleware File System */
/* Keil::Device:CubeMX@1.0.0 */
#define RTE_DEVICE_CUBE_MX
#define CMSIS_device_header "stm32f4xx.h"
/* Keil::USB&MDK-Plus:CORE&Release@6.17.0 */
#define RTE_USB_Core                    /* USB Core */
#define RTE_USB_Core_Release            /* USB Core Release Version */


#endif /* RTE_COMPONENTS_H */
